### PR TITLE
Export Overlay Data by file ID, add FallsWaterDestination MapObj Settings

### LINKED ISSUE #43: Overlay data not exported by FileID
MKTB assumes that the FileID are the same as the overlay ID which is not true and causes the overlays to be exported in the wrong order and be imported without proper FileIDs.

https://github.com/HaroohiePals/MarioKartToolbox/blob/d4ada624f651b9eb8b305014e98175fcda53fc3e/src/HaroohiePals.NitroKart/Rom/MkdsRomProjectFactory.cs#L71-L83
`rom.FileData[entry.Id]` should be referencing `rom.FileData[entry.FileId]` instead.

And there might be other changes needed somewhere else as well because the FileID value is not written back to the table.

### PR DESCRIPTION
**Pull request by rocoloco321**
fixes #43, this commit will require existing rom projects to be re-exported because overlay importing has to be handled differently to be compatible with this change. Unsure how I could keep backwards compatibility with previously exported projects without adding an extra field to the rom project json file.

The FallsWaterDestination MObj settings are there because I forgot I had implemented them months ago

### CODE REVIEW

**Comment by Gericom** [comment]
Maybe a version field would need to be added to the json?

File: src/HaroohiePals.NitroKart/Rom/MkdsRomFactory.cs [hunk 1]
```diff
@@ -82,27 +82,41 @@ private async Task<NdsRomOverlayTable> ReadOverlayTableAsync(string path, uint o
...
-    private async Task<ReadOverlayFilesResult> ReadOverlayFilesAsync(NdsRomOverlayTable overlayTable, string[] overlayPaths, string workingDirPath)
+    private async Task<ReadOverlayFilesResult> ReadOverlayFilesAsync(NdsRomOverlayTable overlayTable, string[] overlayPaths, string workingDirPath, int version)
     {
         var fatEntries = new List<FatEntry>();
         var fileData = new List<byte[]>();
 
         int currFileId = 0;
-
-        while (currFileId < overlayTable.Length)
+        if(version != 0)
```
Comment (Ermelber) [inline src/HaroohiePals.NitroKart/Rom/MkdsRomFactory.cs]: indent properly, also maybe the it should be "version > 0"

File: src/HaroohiePals.NitroKart/Rom/MkdsRomProjectFactory.cs [hunk 2]
```diff
@@ -36,10 +36,13 @@ public async Task<MkdsRomProject> CreateAsync(NdsRom rom, string projectName, st
             Arm7OverlaysPaths = arm7OverlaysPaths
         };
 
+        var version = 1;
```
Comment (Ermelber) [inline src/HaroohiePals.NitroKart/Rom/MkdsRomProjectFactory.cs]:
```suggestion
        int version = 1;
```
According to our code style, we prefer using explicit type declarations for primitive variables such as `int`.

File: src/HaroohiePals.NitroKart/Rom/MkdsRomFactory.cs [hunk 3]
```diff
@@ -82,20 +82,42 @@ private async Task<NdsRomOverlayTable> ReadOverlayTableAsync(string path, uint o
...
+    private async Task<ReadOverlayFilesResult> ReadOverlayFilesAsync(NdsRomOverlayTable overlayTable, string[] overlayPaths, string workingDirPath, int version)
     {
         var fatEntries = new List<FatEntry>();
         var fileData = new List<byte[]>();
 
-        int i = 0;
-
-        foreach (var entry in overlayTable.Entries)
+        int currFileId = 0;
+        if(version != 0)
```
Comment (Ermelber) [inline src/HaroohiePals.NitroKart/Rom/MkdsRomFactory.cs]:
```suggestion
        if (version != 0)
```

Indent properly, also it's better to check for versions greater than 0 instead. Maybe you should also change the version to be `uint` at this point.

File: src/HaroohiePals.NitroKart/Rom/MkdsRomProject.cs [hunk 4]
```diff
@@ -10,4 +10,5 @@ public class MkdsRomProject
 {
     public string Name { get; set; }
     public NdsRomInfo RomInfo { get; set; } = new();
+    public int Version { get; set; } = 0;
```
Comment (Ermelber) [inline src/HaroohiePals.NitroKart/Rom/MkdsRomProject.cs]: Like I said earlier, maybe make the Version field unsigned (`uint`)

**Review by Ermelber — CHANGES_REQUESTED** [review]

**Review by Ermelber — APPROVED** [review]
